name: ganache_lab
description: "Le premier équilibreur de ganache multiplatformes !"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  morphable_shape: ^2.0.0
  flutter_svg: ^2.2.0
  flutter_markdown: ^0.7.7+1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  material_symbols_icons: ^4.2867.0
  yaml: ^3.1.3
  package_rename: ^1.10.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/licenses/LICENSE.md
    - assets/documentations/
    - assets/announces/form.md