name: Deploiement GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write # Obligatoire pour permettre le push sur la branche gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Supprime l'avertissement de deprecation Node.js

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Recuperation des dependances
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href "/Ganache.lab/"

      - name: Deploiement vers GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
