name: Deploiement GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installation de Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true # Améliore la vitesse des builds suivants

      - name: Recuperation des dependances
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release --base-href="/Ganache.lab/" --web-renderer=html

      - name: Deploiement vers GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
